build_config:
  input_shape:
  - null
  - 400
class_name: Sequential
compile_config:
  jit_compile: false
  loss: categorical_crossentropy
  loss_weights: null
  metrics:
  - accuracy
  - class_name: AUC
    config:
      curve: ROC
      dtype: float32
      from_logits: false
      label_weights: null
      multi_label: false
      name: auc
      num_labels: null
      num_thresholds: 200
      summation_method: interpolation
    module: keras.metrics
    registered_name: null
  - class_name: Precision
    config:
      class_id: null
      dtype: float32
      name: precision
      thresholds: null
      top_k: null
    module: keras.metrics
    registered_name: null
  - class_name: Recall
    config:
      class_id: null
      dtype: float32
      name: recall
      thresholds: null
      top_k: null
    module: keras.metrics
    registered_name: null
  optimizer:
    class_name: Adam
    config:
      amsgrad: false
      beta_1: 0.9
      beta_2: 0.999
      clipnorm: null
      clipvalue: null
      ema_momentum: 0.99
      ema_overwrite_frequency: null
      epsilon: 1e-07
      global_clipnorm: null
      gradient_accumulation_steps: null
      learning_rate: 0.0010000000474974513
      loss_scale_factor: null
      name: adam
      use_ema: false
      weight_decay: null
    module: keras.optimizers
    registered_name: null
  run_eagerly: false
  steps_per_execution: 1
  weighted_metrics: null
config:
  build_input_shape:
  - null
  - 400
  dtype:
    class_name: DTypePolicy
    config:
      name: float32
    module: keras
    registered_name: null
  layers:
  - class_name: InputLayer
    config:
      batch_shape:
      - null
      - 400
      dtype: float32
      name: input_layer
      sparse: false
    module: keras.layers
    registered_name: null
  - build_config:
      input_shape:
      - null
      - 400
    class_name: Dense
    config:
      activation: relu
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
        module: keras.initializers
        registered_name: null
      bias_regularizer: null
      dtype:
        class_name: DTypePolicy
        config:
          name: float32
        module: keras
        registered_name: null
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed: null
        module: keras.initializers
        registered_name: null
      kernel_regularizer: null
      name: dense
      trainable: true
      units: 396
      use_bias: true
    module: keras.layers
    registered_name: null
  - class_name: Dropout
    config:
      dtype:
        class_name: DTypePolicy
        config:
          name: float32
        module: keras
        registered_name: null
      name: dropout
      noise_shape: null
      rate: 0.1
      seed: null
      trainable: true
    module: keras.layers
    registered_name: null
  - build_config:
      input_shape:
      - null
      - 396
    class_name: Dense
    config:
      activation: relu
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
        module: keras.initializers
        registered_name: null
      bias_regularizer: null
      dtype:
        class_name: DTypePolicy
        config:
          name: float32
        module: keras
        registered_name: null
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed: null
        module: keras.initializers
        registered_name: null
      kernel_regularizer: null
      name: dense_1
      trainable: true
      units: 198
      use_bias: true
    module: keras.layers
    registered_name: null
  - class_name: Dropout
    config:
      dtype:
        class_name: DTypePolicy
        config:
          name: float32
        module: keras
        registered_name: null
      name: dropout_1
      noise_shape: null
      rate: 0.1
      seed: null
      trainable: true
    module: keras.layers
    registered_name: null
  - build_config:
      input_shape:
      - null
      - 198
    class_name: Dense
    config:
      activation: relu
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
        module: keras.initializers
        registered_name: null
      bias_regularizer: null
      dtype:
        class_name: DTypePolicy
        config:
          name: float32
        module: keras
        registered_name: null
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed: null
        module: keras.initializers
        registered_name: null
      kernel_regularizer: null
      name: dense_2
      trainable: true
      units: 99
      use_bias: true
    module: keras.layers
    registered_name: null
  - class_name: Dropout
    config:
      dtype:
        class_name: DTypePolicy
        config:
          name: float32
        module: keras
        registered_name: null
      name: dropout_2
      noise_shape: null
      rate: 0.1
      seed: null
      trainable: true
    module: keras.layers
    registered_name: null
  - build_config:
      input_shape:
      - null
      - 99
    class_name: Dense
    config:
      activation: softmax
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
        module: keras.initializers
        registered_name: null
      bias_regularizer: null
      dtype:
        class_name: DTypePolicy
        config:
          name: float32
        module: keras
        registered_name: null
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed: null
        module: keras.initializers
        registered_name: null
      kernel_regularizer: null
      name: dense_3
      trainable: true
      units: 3
      use_bias: true
    module: keras.layers
    registered_name: null
  name: sequential
  trainable: true
module: keras
registered_name: null
